name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: justgook/setup-elm@1.3.0
        with:
          elm-version: '0.19.1'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save-dev ts-loader
      - run: make build
      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add main.js
          git checkout -b release
          git commit -m "Automated file generation"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/tedbauer/tedbauer.github.io HEAD:release --force
